apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  storageClassName: gp3
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
